language: ruby

rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7

env:
  - NUODB_ROOT=/opt/nuodb
  - RUBY_ROOT=/

notifications:
  recipients:
    - buck.robert.j@gmail.com
    - rbuck@nuodb.com

before_script:
  - make install

script:
  - make all

after_script:
  - make uninstall