language: ruby
rvm:
  - 1.9.3
notifications:
  recipients:
    - buck.robert.j@gmail.com
branches:
  only:
    master
env:
  global:
    NUODB_ROOT=/opt/nuodb
script: bundle exec rake nuodb:install install nuodb:remove
